apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-component-yxtvwx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-component-yxtvwx
    app.kubernetes.io/part-of: build-suite-positive-mc-myse
  name: go-component-yxtvwx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: go-component-yxtvwx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: go-component-yxtvwx
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-rapx-tenant/build-suite-positive-mc-myse/go-component-yxtvwx@sha256:3125570cfa16fe941febd0257d8607aa44da8d85ef0031cf04023c6e48bb9ea8
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
